export type SplunkApp = {
  id: number;
  app_id: string;
  product_compatibility: string;
  product_types: string[];
  app_name: string;
  description: string;
  created_time: string;
  published_time: string;
  updated_time: string;
  app_type: string;
  contact_email: string;
  contact_notes: string;
  access: string;
  approved: boolean;
  inquiry_url: string;
  inquiry_buttontext: string;
  price: string;
  license_name: string;
  license_url: string;
  appinspect_passed: true;
  display_editors: boolean;
  is_directory_listing: boolean;
  is_splunk_built: boolean;
  is_soar_certified: boolean;
  cloud_compatible: boolean;
  archive_status: string;
  is_archived: boolean;
  fedramp_validation: 'yes' | 'no';
  contains_encryption: boolean;
  download_count: number;
  install_count: number;
  app_url: string;
  video_link: string;
};
